version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      rspack:
        patterns:
          - "@rspack/*"
